{{- if eq .Values.connector "okta"}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.okta.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  apiToken: {{ .Values.okta.apiToken | b64enc }}
{{- end}}
